### ISSUE TITLE
Bring global styling more inline with current cg-style practices.

### ISSUE THREAD

**Issue by DavidEBest** [18F/compliance-viewer#31]
Breaking out from #28 
- [x] Remove background image and style similar to https://cloud.gov/updates/
- [x] Add footer cloud.gov styling

**Comment by afeld** [comment]
> Remove background image and style similar to https://cloud.gov/updates/

Is that a new design, or an old one?

/cc @msecret @jeremiak @rtwell

**Comment by juliasolorzano** [comment]
@afeld I don't think this style is necessarily "new" but a different template style than other pages (e.g. homepage). Does that make sense?

**Comment by afeld** [comment]
I just asked @jeremiak in person, and he said that the pages _should_ have a blue background. "docs.cloud.gov is the style to match." Am I misunderstanding something?

**Comment by juliasolorzano** [comment]
Just to clarify, is the styling for this page incorrect?

https://cloud.gov/updates/

**Comment by msecret** [comment]
@afeld `/updates` wasn't exclusively worked on, so I would say it _could_ be incorrect, but more it wasn't thought of. 

In terms of background, cloud.gov has a background color scheme with alternative dark and light backgrounds while docs has a dark background with white content section. There's a bug on docs where the sidenav should but the same blue color down the whole page, and the hexagons should be to the left of the sidenav, not to the left of the main content section. I'll probably come up with a fix soon so those hexagons are always to the left of the content. 

I think we need a visual designer to help with some of these decisions. My personal preference is that there's no strict definitions of what the background colors and configurations should be, but they shouldn't differ drastically from the style guide(such as using a completely different color). So I would say the look on the `/updates` page is fine, but should be reviewed by a visual designer to confirm.

**Comment by juliasolorzano** [comment]
@msecret quick note! @rtwell has kindly offered to give us some screens to work with.

My two cents are to go ahead and merge this in for now and update with his styles on they are completed. What say you all?

**Comment by juliasolorzano** [comment]
Update: talked further with @rtwell on the styling and received some great direction from him (when we are ready). Onward and thanks all!
