### ISSUE TITLE
Improve styling on the report page

### ISSUE THREAD

**Issue by DavidEBest** [18F/compliance-viewer#32]
Breaking out from #28 
- [x] Add back arrow to "Project List page" link at the top of the page
- [x] Add spacing (see wireframe) for the top portion of the page (see image below).
- [x] Make "Updated..." italicized
- [x] Add relevant links to each bullet point under "Getting Started"
  - First one: https://pages.18f.gov/before-you-ship/
  - Second one: https://pages.18f.gov/before-you-ship/ato/checklist/
- [x] Add a visual indicator for sortability to the Type & Risk columns

Wireframe
![cv-wireframes-v3_page_3](https://cloud.githubusercontent.com/assets/955558/14959804/2e7bb4d6-105f-11e6-9ca2-c886abdf90ad.png)

**Comment by jseppi** [comment]
Working on this one.

**Comment by jseppi** [comment]
Finished with all in 89e159edd8995791b610713a1258936bdce2f5db except the back arrow.

@juliaelman Do we have an image/svg to use for that back arrow?

**Comment by juliasolorzano** [comment]
@jseppi we do not and would recommend using `&#8592;` character encoding for now.
