### ISSUE TITLE
Improve styling on results list page

### ISSUE THREAD

**Issue by DavidEBest** [18F/compliance-viewer#33]
The results page should be updated to reflect the wireframe.
- [x] Add welcome headline and description verbiage from https://drive.google.com/a/gsa.gov/file/d/0B_NVRFrsefnvQW5pQXZCSzE1WjQ/view
- [x] Move project links into sortable table
- [x] Make table links function as links to the appropriate report page.

https://drive.google.com/a/gsa.gov/file/d/0B_NVRFrsefnvQW5pQXZCSzE1WjQ/view

**Comment by jseppi** [comment]
I can do this if nobody has started yet.

**Comment by DavidEBest** [comment]
@jseppi Go for it!

**Comment by DavidEBest** [comment]
unless @juliaelman has started on it. :)

**Comment by juliasolorzano** [comment]
Go for it!

**Comment by jseppi** [comment]
Do we have the description copy for this page yet?

**Comment by DavidEBest** [comment]
@jseppi: It is being worked on here: https://docs.google.com/a/gsa.gov/document/d/1Kb0wb_yqLUHYWA-icSYoA5TbYSGEe50p35Ik4S6oETY/edit?usp=sharing. Feel free to grab a snapshot of it.
