### ISSUE TITLE
Reports page - what to show when there are no scan errors

### ISSUE THREAD

**Issue by jseppi** [18F/compliance-viewer#38]
Table of scan errors removed and a message shown instead?

**Comment by DavidEBest** [comment]
Yes. Something big and friendly, like:

Good work! The last scan returned no alerts.

@juliaelman Thoughts?

**Comment by juliasolorzano** [comment]
Hrmmm... it should probably say "All scans passing" for now.

**Comment by jseppi** [comment]
I'll do this real quick

**Comment by jseppi** [comment]
How is this, using `.usa-alert-success`:

<img width="1001" alt="screen shot 2016-05-03 at 10 46 05 am" src="https://cloud.githubusercontent.com/assets/697848/14989137/0ac124dc-111c-11e6-85e9-55f27a86d152.png">

**Comment by DavidEBest** [comment]
@jseppi Works for me.

**Comment by juliasolorzano** [comment]
Maybe let's not add any icon on here for now and make the text inline. Simple and clean 😄
